### ISSUE TITLE
能否开放PCB和BOM文件

### ISSUE THREAD

**Issue by xiedonghuilove** [Cai-Zi/STM32_T12_Controller#1]
你好，兄弟，能不能开放你这个项目的PCB文件和BOM文件，我想自己DIY一个学习学习。

**Comment by Cai-Zi** [comment]
还没设计PCB，后面会出教程，元件清单会列进去

**Comment by Cai-Zi** [comment]
PCB已发布在立创开源广场https://oshwhub.com/caisheng/T12han-tai-kong-zhi-qi
